### ISSUE TITLE
Running into issues on mac

### ISSUE THREAD

**Issue by abhijithch** [jverzani/DThree.jl#2]
I am trying out some of the examples shown on a mac. I would like to know if there are any pre-requisites for making things work line `Electron` etc.

**Comment by jverzani** [comment]
Disclaimer: I don't think this package is too useful. But to answer your question,
I don't think so. It could just be the examples are broken. I recently did a bit of work on this. What is working is the Plots package interface. So if this doesn't work, then the installation isn't right:

```
using DThree, Plots
plotly()
plot(sin, 0, 2pi)
```

**Comment by jverzani** [comment]
If you are still interested, I had forgot to push this change: b7ef9201bb54d490b54e999c7697f6696701de9f  The main example should work now.

**Comment by abhijithch** [comment]
Thanks this works.
